import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/Components/Navbar";
import Suugestion from "@/app/Components/Suugestion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <section className={'flex w-full justify-between'}>
          <Navbar/>
          {children}
          <Suugestion/>
      </section>
      </body>
    </html>
  );
}
